//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderProcessingLocalTestClient.OrderProcessing {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderProcessing.IOrderProcessing")]
    public interface IOrderProcessing {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProcessing/OrderStatusRequest", ReplyAction="http://tempuri.org/IOrderProcessing/OrderStatusRequestResponse")]
        ServiceLibrary.DataContracts.OrderStatusResult OrderStatusRequest(ServiceLibrary.DataContracts.OrderStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProcessing/GetShippingRequest", ReplyAction="http://tempuri.org/IOrderProcessing/GetShippingRequestResponse")]
        ServiceLibrary.DataContracts.ShippingInfoResult GetShippingRequest(ServiceLibrary.DataContracts.ShippingInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProcessing/SubmitOrder", ReplyAction="http://tempuri.org/IOrderProcessing/SubmitOrderResponse")]
        ServiceLibrary.DataContracts.SubmitOrderResult SubmitOrder(ServiceLibrary.DataContracts.SubmitOrderRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderProcessingChannel : OrderProcessingLocalTestClient.OrderProcessing.IOrderProcessing, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderProcessingClient : System.ServiceModel.ClientBase<OrderProcessingLocalTestClient.OrderProcessing.IOrderProcessing>, OrderProcessingLocalTestClient.OrderProcessing.IOrderProcessing {
        
        public OrderProcessingClient() {
        }
        
        public OrderProcessingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderProcessingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderProcessingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderProcessingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceLibrary.DataContracts.OrderStatusResult OrderStatusRequest(ServiceLibrary.DataContracts.OrderStatusRequest request) {
            return base.Channel.OrderStatusRequest(request);
        }
        
        public ServiceLibrary.DataContracts.ShippingInfoResult GetShippingRequest(ServiceLibrary.DataContracts.ShippingInfoRequest request) {
            return base.Channel.GetShippingRequest(request);
        }
        
        public ServiceLibrary.DataContracts.SubmitOrderResult SubmitOrder(ServiceLibrary.DataContracts.SubmitOrderRequest request) {
            return base.Channel.SubmitOrder(request);
        }
    }
}
